version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          name: Install deps
          command: pip install -r tests/requirements-tests.txt
      - python/save-cache
      - setup_remote_docker
      - run:
          name: Start container and verify it is working
          command: |
            set -x
            docker-compose up -d
      - run:
          name: Test  
          command: python3 tests/tests.py
            

workflows:
  main:
    jobs:
      - build-and-test
