version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start container and verify it is working
          command: |
            set -x
            docker-compose up -d
      - run:
          name: Test  
          command: ./run_tests.sh
            

workflows:
  main:
    jobs:
      - build-and-test
